
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig} from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    /* process.env.DATABASE_URL is used at runtime (from .env or EC2 user data).
     The fallback is only used during 'prisma generate' in CI, which generates
     client code and never actually connects to a database.
    */
    url: process.env.DATABASE_URL ?? "postgresql://build:build@localhost:5432/csye6225",
  },
});
